{
    "swagger": "2.0",
    "info": {
        "description": "Producer service standard version 1.0",
        "version": "1.0",
        "title": "Producer service example specification v1.0",
        "contact": {},
        "license": {
            "url": "http://unlicense.org"
        }
    },
    "host": "localhost:8081",
    "basePath": "/",
    "tags": [
        {
            "name": "hello-api-controller",
            "description": "Producer service API"
        }
    ],
    "paths": {
        "/api/hello/{userName}": {
            "get": {
                "tags": [
                    "Hello"
                ],
                "summary": "Get Hello",
                "operationId": "getHelloMessage",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "userName",
                        "in": "path",
                        "description": "userName",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    },
                    "429": {
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "deprecated": false
            }
        }
    }
}
