AWSTemplateFormatVersion: '2010-09-09'
Description: container on ecs cluster
Parameters:
  NetworkStackName:
    Type: String
    Description: The name of the network stack.
  IAMStackName:
    Type: String
    Description: The name of the IAM stack.
  ClusterStackName:
    Type: String
    Description: The name of the cluster stack.


Resources:
  Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: atlas
      Cpu: 512
      Memory: 1024 
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: 
            !Join [':', [ !Ref 'IAMStackName', 'ECSTaskExecutionRole']]
      ContainerDefinitions:
        - Name: consumer-service
          Image: synrgroup/consumer-service-demo-01:2
          Environment:
            - Name: consumer.producerServiceUrl
              Value: http://producerservice.projectname.com:8081 
          Cpu: 512
          Memory: 1024
          PortMappings:
            - ContainerPort: 8082
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'projectname-log'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'consumer-service'


  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      ServiceName: consumer-service
      TaskDefinition: !Ref Task
      Cluster: 
        Fn::ImportValue: 
          !Join [':',[!Ref 'ClusterStackName','ECSCluster']]
      LaunchType: FARGATE
      DesiredCount: 1
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: !Join [':',[!Ref 'NetworkStackName','Subnet1']] 
            - Fn::ImportValue: !Join [':',[!Ref 'NetworkStackName','Subnet2']] 
          SecurityGroups:
            - Fn::ImportValue: !Join [':',[!Ref 'NetworkStackName','ContainerSecurityGroup']]  
      LoadBalancers:
        - ContainerName: consumer-service
          ContainerPort: 8082
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: consumer-tg
      VpcId: 
        Fn::ImportValue: 
          !Join [':',[!Ref 'NetworkStackName','Vpc']]
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /api-docs
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: 
        Fn::ImportValue: 
          !Join [':',[!Ref 'NetworkStackName','Listener']] 
      Priority: 3
      Conditions:
        - Field: path-pattern
          Values:
            - /consumer/*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
