version: "3.8"
services:
  producer:
    container_name: producer-service
    image: synrgroup/producer-service-demo-01:latest
    networks:
      - test-network
    ports:
      - 8081:8081

  consumer:
    container_name: consumer-service
    image: synrgroup/consumer-service-demo-01:latest
    networks:
      - test-network
    environment:
      consumer.producerServiceUrl: "http://producer.dockercompose.local:8081"
    ports:
      - 8082:8082

networks:
  test-network:
