version: "3.7"
services:
  producer-service:
    container_name: producer-service
    image: synrgroup/producer-service-demo-01:latest
    networks:
      - test-network
    ports:
      - 8081:8081

  consumer-service:
    container_name: consumer-service
    image: synrgroup/consumer-service-demo-01:latest
    networks:
      - test-network
    environment:
      consumer.producerServiceUrl: "${PRODUCER_SERVICE_URL}"
    ports:
      - 8082:8082


networks:
    test-network: